### ISSUE TITLE
issue#1 - can't find module request

### ISSUE THREAD

**Issue by dolniaciiik** [flamebarke/coronavirus#1]
$ python3 coronavirus.py
Traceback (most recent call last):
  File "coronavirus.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by flamebarke** [comment]
This is due to missing modules. I've added a requirements.txt file that you can use to install the required modules.

do:

`pip3 install -r requirements.txt`
